version: '3.8'

services:
  moodle:
    image: bitnami/moodle:4
    container_name: moodle
    restart: always
    ports:
      - "8080:8080"
    environment:
      - MOODLE_DATABASE_TYPE=${MOODLE_DATABASE_TYPE}
      - MOODLE_DATABASE_HOST=${MOODLE_DATABASE_HOST}
      - MOODLE_DATABASE_PORT_NUMBER=${MOODLE_DATABASE_PORT_NUMBER}
      - MOODLE_DATABASE_NAME=${MOODLE_DATABASE_NAME}
      - MOODLE_DATABASE_USER=${MOODLE_DATABASE_USER}
      - MOODLE_DATABASE_PASSWORD=${MOODLE_DATABASE_PASSWORD}
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      - MOODLE_EMAIL=${MOODLE_EMAIL}
    volumes:
      - ./moodle:/bitnami/moodle
      - ./moodledata:/bitnami/moodledata
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - moodle_network
      - postgres_network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - postgres_network

networks:
  moodle_network:
    driver: bridge
  postgres_network:
    internal: true